version: '3.9'

name: forest-admin

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forest-backend
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forest-backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.forest-backend.entrypoints=websecure"
      - "traefik.http.routers.forest-backend.tls.certresolver=myresolver"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      FOREST_ENV_SECRET: ${FOREST_ENV_SECRET}
      FOREST_AUTH_SECRET: ${FOREST_AUTH_SECRET}
    volumes:
      - .:/usr/src/app
    restart: always

  postgres:
    image: postgres:15
    container_name: forest-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  traefik:
    image: traefik:v2.10
    container_name: forest-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=websecure"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    restart: always

volumes:
  postgres_data:
  letsencrypt:
