version: '3.9'

name: forest-admin

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forest-backend
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forest-backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.forest-backend.entrypoints=websecure"
      - "traefik.http.routers.forest-backend.tls.certresolver=myresolver"
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      FOREST_ENV_SECRET: ${FOREST_ENV_SECRET}
      FOREST_AUTH_SECRET: ${FOREST_AUTH_SECRET}
    volumes:
      - .:/usr/src/app
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: forest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    env_file:
      - .env
    restart: always

  traefik:
    image: traefik:v2.10
    container_name: forest-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=websecure"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    restart: always

volumes:
  mongodb_data:
  letsencrypt:
